# Generated by Django 5.2.17 on 2026-09-11 21:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('note_revision', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Clock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.PositiveBigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('ability', 'Умение'), ('item', 'Снаряжение'), ('race', 'Раса'), ('class', 'Класс'), ('school', 'Школа'), ('background', 'Предыстория'), ('craft', 'Ремесло'), ('keyword', 'Ключевое слово'), ('specialization', 'Специализация'), ('effect', 'Эффект')], max_length=30)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('archived', models.BooleanField(default=False)),
                ('source', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.JSONField(default=dict)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('level', models.PositiveSmallIntegerField(default=1)),
                ('info', models.JSONField(default=dict)),
                ('stats', models.JSONField(default=dict)),
                ('runtime', models.JSONField(default=dict)),
                ('private_notes', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, upload_to='portraits/')),
                ('revision', models.PositiveIntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('abilities', models.ManyToManyField(blank=True, related_name='characters', to='game.entry')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('before', models.JSONField(default=dict)),
                ('after', models.JSONField(default=dict)),
                ('undone', models.BooleanField(default=False)),
                ('redoable', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('scene', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='game.scene')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='game.campaign')),
                ('characters', models.ManyToManyField(to='game.character')),
            ],
        ),
        migrations.AddField(
            model_name='scene',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='game.session'),
        ),
        migrations.CreateModel(
            name='Squad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='squads', to='game.campaign')),
            ],
        ),
        migrations.AddField(
            model_name='session',
            name='squad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='game.squad'),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('equipped', models.BooleanField(default=False)),
                ('slot', models.CharField(blank=True, max_length=40)),
                ('data', models.JSONField(default=dict)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='game.campaign')),
                ('character', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='game.character')),
                ('entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.entry')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('campaign__isnull', True), ('character__isnull', False)), models.Q(('campaign__isnull', False), ('character__isnull', True)), _connector='OR'), name='item_one_owner')],
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=80)),
                ('result', models.JSONField(default=dict)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('actor', 'key'), name='unique_command')],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='game.campaign')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='game.character')),
                ('squad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.squad')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('character', 'campaign'), name='one_membership')],
            },
        ),
    ]
