# Generated by Django 5.2.17 on 2026-09-11 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='inputs',
            field=models.JSONField(default=dict),
        ),
    ]
