# Generated by Django 5.2.17 on 2026-09-11 23:07

from django.conf import settings
from django.db import migrations, models


def existing_players(apps, schema_editor):
    Campaign = apps.get_model('game', 'Campaign')
    Membership = apps.get_model('game', 'Membership')
    for campaign in Campaign.objects.all():
        owners = Membership.objects.filter(campaign=campaign).values_list('character__owner_id', flat=True).distinct()
        campaign.players.add(*owners)


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_event_inputs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='players',
            field=models.ManyToManyField(blank=True, related_name='campaigns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(existing_players, migrations.RunPython.noop),
    ]
