# Generated by Django 5.2.17 on 2026-09-11 23:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_campaign_players'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('quest', 'Квест'), ('note', 'Запись'), ('lore', 'Мир')], default='quest', max_length=10)),
                ('title', models.CharField(max_length=160)),
                ('body', models.TextField(blank=True)),
                ('person', models.CharField(blank=True, max_length=160)),
                ('reward', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('active', 'В работе'), ('done', 'Выполнено'), ('paused', 'Отложено'), ('failed', 'Провалено')], default='active', max_length=10)),
                ('steps', models.JSONField(blank=True, default=list)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('archived', models.BooleanField(default=False)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal', to='game.campaign')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated', '-id'],
            },
        ),
    ]
