# Generated by Django 5.2.17 on 2026-09-12 00:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_journalentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Knowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('recipe', 'Рецепт'), ('contact', 'Контакт'), ('lore', 'Запись')], max_length=12)),
                ('title', models.CharField(max_length=160)),
                ('body', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('details', models.CharField(blank=True, max_length=1000)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('private', models.BooleanField(default=True)),
                ('archived', models.BooleanField(default=False)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge', to='game.character')),
                ('entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.entry')),
            ],
            options={
                'ordering': ['title', 'id'],
            },
        ),
    ]
