# Generated by Django 5.2.17 on 2026-09-12 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_knowledge'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='revision',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
