# Generated by Django 5.2.17 on 2026-09-12 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_item_archived_item_revision'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='personal_character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personal_abilities', to='game.character'),
        ),
    ]
