# Generated by Django 5.2.17 on 2026-09-12 04:48

import django.db.models.deletion
from django.db import migrations, models


def link_existing_versions(apps,schema_editor):
    Entry=apps.get_model('game','Entry')
    for personal in Entry.objects.filter(personal_character__isnull=False,source_entry__isnull=True):
        candidates=Entry.objects.filter(personal_character__isnull=True,kind=personal.kind)
        candidates=candidates.filter(source=personal.source) if personal.source else candidates.filter(name=personal.name)
        ids=list(candidates.values_list('pk',flat=True)[:2])
        if len(ids)==1:
            personal.source_entry_id=ids[0]
            personal.save(update_fields=['source_entry'])


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_entry_personal_character'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='source_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personal_versions', to='game.entry'),
        ),
        migrations.RunPython(link_existing_versions,migrations.RunPython.noop),
    ]
